#!/usr/bin/env python3
import sys
import os
import rclpy
from rclpy.node import Node
from std_msgs.msg import String

try:
    from talker_pkg import ros_config_pb2
    from intrinsic.resources.proto import runtime_context_pb2
except ImportError as e:
    print(f"Import Error: {e}. Be sure that the packages are correctly compilated.")
    sys.exit(1)

def get_runtime_context():
    config_path = "/etc/intrinsic/runtime_config.pb"
    runtime_context = runtime_context_pb2.RuntimeContext()
    
    if os.path.exists(config_path):
        with open(config_path, "rb") as f:
            runtime_context.ParseFromString(f.read())
    else:
        print("Achtung: /etc/intrinsic/runtime_config.pb not found. Using empty context.")
    return runtime_context

class MinimalPublisher(Node):
    def __init__(self):
        super().__init__('minimal_publisher')
        self.publisher_ = self.create_publisher(String, 'topic', 10)
        self.timer = self.create_timer(1.0, self.timer_callback)
        self.count = 0

    def timer_callback(self):
        msg = String()
        msg.data = f'ROS 2 message from Intrinsic: {self.count}'
        self.publisher_.publish(msg)
        self.get_logger().info(f'Publishing: "{msg.data}"')
        self.count += 1

def main(args=None):
    runtime_context = get_runtime_context()
    ros_config = ros_config_pb2.RosConfig()
    
    if runtime_context.config.Is(ros_config.DESCRIPTOR):
        runtime_context.config.Unpack(ros_config)

    intrinsic_ros_args = list(ros_config.ros_args)
    combined_args = sys.argv + ["--ros-args"] + intrinsic_ros_args
    
    rclpy.init(args=combined_args)
    
    node = MinimalPublisher()
    
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
